### ISSUE TITLE
Requires ToJSON instance for Headers

### ISSUE THREAD

**Issue by RocketPuppy** [plow-technologies/servant-aeson-specs#5]
If I have an API that looks something like this:

```
type API = Post '[JSON] (Headers '[Header "Set-Cookie" ByteString] Int)
```

and a test like:

```
apiRoundTripSpecs (Proxy :: Proxy API)
```

I'm forced to provide a ToJSON instance for `Headers '[Header "Set-Cookie" ByteString] Int`. I would think that it should ignore the Headers and just test JSON conversion for Int.

**Comment by RocketPuppy** [comment]
Played around with it some more and came up with these instances that seem to be missing:

```
instance MkTypeSpecs a => HasGenericSpecs (Verb (method :: StdMethod) returnStatus contentTypes (Headers hs a)) where
    collectRoundtripSpecs _ = mkTypeSpecs (Proxy :: Proxy a)

instance HasGenericSpecs rest  => HasGenericSpecs (AuthProtect (sym :: Symbol) :> rest) where
    collectRoundtripSpecs _ = collectRoundtripSpecs (Proxy :: Proxy rest)

instance HasGenericSpecs rest  => HasGenericSpecs (Capture (sym :: Symbol) x :> rest) where
    collectRoundtripSpecs _ = collectRoundtripSpecs (Proxy :: Proxy rest)
```

If you see nothing wrong with these instances, I'll have some more time to write up a PR later in the week.

**Comment by mchaver** [comment]
That would be great if you make a PR. Just be sure to add tests for everything you add.

**Comment by mchaver** [comment]
Your PR has been merged and pushed to hackage. Version number is 0.5.1.0. I made a request to add it to stackage.
